- hosts: localhost
  vars:
    deb_architecture: { "aarch64": "arm64", "x86_64": "amd64" }
    home: "{{ lookup('env', 'HOME') }}"
    user: "{{ lookup('env', 'USER') }}"
    bin: "{{ home }}/.local/bin"
    zsh_custom: "{{ home }}/.oh-my-zsh/custom"
    git_default_profile: personal
    git_profiles:
      personal:
        name: JohnPosada
        email: johnposada2000@gmail.com
        github_user: JohnPosada
      work:
        name: JohnPosada-arago
        email: 197618135+JohnPosada-arago@users.noreply.github.com
        github_user: JohnPosada-arago
        signingkey: 057B577BE58D0988
        dirs:
          - "~/arago/"
          - "~/CFdocgenerator/"
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags: always

    - name: Install Ansible module dependencies
      become: true
      apt:
        name: ["python3-debian"]
        state: present
      tags: always
  tasks:
    - import_tasks: tasks/folders.yml
    - import_tasks: tasks/deb.yml
    - import_tasks: common/fonts.yml
    - import_tasks: common/neovim.yml 
    - import_tasks: common/lazy.yml
    - import_tasks: common/node.yml
    - import_tasks: tasks/apt.yml
    - import_tasks: tasks/docker.yml
    - import_tasks: tasks/flatpak.yml
    - import_tasks: tasks/kitty.yml
    - import_tasks: tasks/npm-packages.yml
    - import_tasks: tasks/zsh.yml
    - import_tasks: tasks/atuin.yml
    - import_tasks: common/oh-my-zsh.yml
    - import_tasks: tasks/git.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/claude.yml