- name: install apt packages
  block:
  - name: "Install system packages"
    become: true
    apt:
      name:
        [
          "unzip",
          "tree",
          "fd-find",
          "curl",
          "ripgrep",
          "copyq",
          "xclip",
          "direnv",
          "feh",
          "stow",
          "flameshot",
          "apt-show-versions",
          "git-extras",
          "bat",
          "tmux",
          "cpu-checker",
          "xbindkeys",
          "gnome-tweaks", 
          "bashtop",
          "git-filter-repo",
          "gimp",
          "python3-pip",
        ]
      state: present

  - name: "Install docker required packages"
    become: true
    apt:
      name: ["ca-certificates", "curl", "gnupg"]
      state: present
    
  tags:
    - apt
    - install