- name: install deb packages
  block:
  - name: "Download Google Chrome .deb package"
    get_url:
      url: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
      dest: "/tmp/google-chrome-stable_current_amd64.deb"

  - name: "Install Google Chrome"
    become: true
    apt:
      deb: "/tmp/google-chrome-stable_current_amd64.deb"

  - name: "Ensure Google Chrome is up to date"
    apt:
      name: google-chrome-stable
      state: latest

  - name: "Download Discord .deb package"
    get_url:
      url: "https://discord.com/api/download?platform=linux&format=deb"
      dest: "/tmp/discord.deb"

  - name: "Install Discord"
    become: true
    apt:
      deb: "/tmp/discord.deb"

  - name: "Remove downloaded .deb packages"
    file:
      path: "/tmp/{{ item }}"
      state: absent
    loop:
      - google-chrome-stable_current_amd64.deb
      - discord.deb

  tags:
    - deb
    - install