- name: install deb packages
  block:
  - name: "Add Google Chrome signing key"
    become: true
    get_url:
      url: "https://dl.google.com/linux/linux_signing_key.pub"
      dest: "/etc/apt/keyrings/google-chrome.asc"
      mode: "0644"

  - name: "Add Google Chrome repository"
    become: true
    deb822_repository:
      name: google-chrome
      types: deb
      uris: "https://dl.google.com/linux/chrome/deb/"
      suites: stable
      components: main
      architectures: amd64
      signed_by: /etc/apt/keyrings/google-chrome.asc

  - name: "Install Google Chrome"
    become: true
    apt:
      name: google-chrome-stable
      state: latest
      update_cache: true

  - name: "Download Discord .deb package"
    get_url:
      url: "https://discord.com/api/download?platform=linux&format=deb"
      dest: "/tmp/discord.deb"

  - name: "Install Discord"
    become: true
    apt:
      deb: "/tmp/discord.deb"

  - name: "Remove downloaded .deb packages"
    file:
      path: "/tmp/discord.deb"
      state: absent

  tags:
    - deb
    - install
