- name: "Install Docker"
  block:
  - name: "Update apt cache"
    become: true
    apt:
      update_cache: yes

  - name: "Install required packages"
    become: true
    apt:
      name: ["ca-certificates", "curl", "gnupg"]
      state: present

  - name: "Create directory for keyrings"
    become: true
    file:
      path: /etc/apt/keyrings
      state: directory
      mode: "0755"

  - name: "Import Docker GPG key"
    become: true
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
      keyring: /etc/apt/keyrings/docker.gpg

  - name: "Set permissions for Docker GPG key"
    become: true
    file:
      path: /etc/apt/keyrings/docker.gpg
      mode: "0644"

  - name: Add Docker repository entry to sources.list.d
    become: true
    lineinfile:
      path: /etc/apt/sources.list.d/docker.list
      line: "deb [arch={{ deb_architecture[ansible_architecture] }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      create: yes
      state: present

  - name: Update apt cache
    become: true
    apt:
      force_apt_get: true
      update_cache: true

  - name: Install Docker packages and plugins
    become: true
    apt:
      force_apt_get: true
      name:
        [
          "docker-ce",
          "docker-ce-cli",
          "containerd.io",
          "docker-buildx-plugin",
          "docker-compose-plugin",
        ]
      state: present

  - name: Create docker group
    become: true
    group:
      name: docker
      state: present
    check_mode: no

  - name: Add user to docker group
    become: true
    user:
      name: "{{ user }}"
      groups: docker
      append: yes

  tags:
    - docker
    - install