- name: "Setup dotfiles using Stow"
  block:
    - name: "Ensure Stow is installed"
      become: true
      apt:
        name: stow
        state: present

    - name: "Clone dotfiles repository"
      git:
        repo: "https://github.com/JohnPosada/dotfiles.git"
        dest: "~/dotfiles"
        update: yes

    - name: "execute Stow to create symlinks and overwrite files"
      shell: |
        stow -v --adopt --override=.* {{ item }}
      args:
        chdir: "~/dotfiles"
        executable: /bin/bash
      loop: "{{ dotfiles }}"

  vars:
    dotfiles:
      - gitconfig
      - zsh
      - nvim
  tags:
    - dotfiles
    - install