- name: "Install flatpak apps"
  block:
  - name: "install flatpak"
    become: true
    apt:
      name: ["flatpak"]
      state: present

  - name: "Add Flathub remote repository"
    community.general.flatpak_remote:
      name: flathub
      flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
      method: user
      state: present

  - name: "Install flatpak apps"
    community.general.flatpak:
      name: "{{ flatpak_apps }}"
      remote: flathub
      method: user
      state: present

  vars:
    flatpak_apps:
      - com.slack.Slack
      - io.dbeaver.DBeaverCommunity
      - com.microsoft.Edge
      - com.spotify.Client
      - com.obsproject.Studio

  tags:
    - flatpak
    - install
