- name: "Install flatpak apps"
  block:
  - name: "install flatpak"
    become: true
    apt:
      name: ["flatpak"]
      state: present

  - name: "Add Flathub remote repository"
    shell: flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

  - name: "Install slack client"
    become: true
    flatpak:
      name: https://dl.flathub.org/repo/appstream/com.slack.Slack.flatpakref
      method: user
      state: present

  - name: "Install dbeaver client"
    become: true
    flatpak:
      name: https://dl.flathub.org/repo/appstream/io.dbeaver.DBeaverCommunity.flatpakref
      method: user
      state: present
  
  - name: "Install edge"
    become: true
    flatpak:
      name: https://dl.flathub.org/repo/appstream/com.microsoft.Edge.flatpakref
      method: user
      state: present
  
  - name: "Install spotify client"
    become: true
    flatpak:
      name: https://dl.flathub.org/repo/appstream/com.spotify.Client.flatpakref
      method: user
      state: present


  - name: "Install obs studio"
    become: true
    flatpak:
      name: https://dl.flathub.org/repo/appstream/com.obsproject.Studio.flatpakref
      method: user
      state: present
  

  tags:
    - flatpak
    - install



