- name: "Install kitty"
  block:
  - name: "Descargar e instalar Kitty desde curl"
    shell: |
      curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
    args:
        executable: /bin/bash

  - name: "Mover el binario de Kitty al sistema"
    shell: |
      mkdir -p ~/.local/bin
      ln -sf ~/.local/kitty.app/bin/kitty ~/.local/bin/
    args:
      executable: /bin/bash

  tags:
    - kitty
    - terminal
    - install
