- name : "Install zsh"
  block:
  - name: "Install zsh"
    become: true
    apt:
      name: ["zsh"]
      state: present

  - name: "Change shell to zsh"
    become: true
    user:
      name: "{{ ansible_user_id }}"
      shell: /bin/zsh

  - name: Clone fzf repository
    git:
      repo: "https://github.com/junegunn/fzf.git"
      dest: "{{ ansible_env.HOME }}/.fzf"
      depth: 1

  - name: Run fzf installation script
    shell: "{{ ansible_env.HOME }}/.fzf/install --all"
    args:
      executable: /bin/bash

  tags:
    - zsh
    - terminal
    - install
